#!/usr/bin/env python3

""" Algernon should run GUI when: $ alger-gui """

import logging
from rich import console
from rich.logging import RichHandler

# 1. Import QApplication and all the required widgets
from PyQt6.QtWidgets import QApplication, QLabel, QWidget

